version: '3'

services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    image: moja-strona:v1
    container_name: web-kontener-1
    ports:
      - "8081:80"
    volumes:
      - ./index1.html:/usr/share/nginx/html/index.html:ro

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    image: moja-strona:v1
    container_name: web-kontener-2
    ports:
      - "8082:80"
    volumes:
      - ./index2.html:/usr/share/nginx/html/index.html:ro

  web3:
    build:
      context: .
      dockerfile: Dockerfile
    image: moja-strona:v1
    container_name: web-kontener-3
    ports:
      - "8083:80"
    volumes:
      - ./index3.html:/usr/share/nginx/html/index.html:ro
