version: '3.8'

services:
  webserver:
    container_name: debian-webserver
    image: debian-webserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    restart: unless-stopped
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  webnet:
    driver: bridge
